Repository PaloAltoNetworks/prisma-cloud-docs, pull requests merged in 2022-12, with the labels that each got.

#678 [Compute API] GH#36823 : Update scan_post.md
  api/descriptions/registry/scan_post.md
Labels: compute-api, docs

#683 [Compute API] : Updated topic map, supported.cfg, and missing files
  api/_topic_map.yml
  api/descriptions/policies/firewall_network_container_get.md
  api/descriptions/policies/firewall_network_container_put.md
  api/descriptions/vms/download_get.md
  api/descriptions/vms/labels_get.md
  api/descriptions/vms/names_get.md
  api/descriptions/vms/scan_post.md
  api/descriptions/vms/stop_post.md
  api/supported.cfg
Labels: compute-api, docs

#686 [CWP-36091 and CWP-41843]: Updated supported.cfg and added information for the missing VM Image Scan
  api/_topic_map.yml
  api/descriptions/vms/download_get.md
  api/descriptions/vms/get.md
  api/descriptions/vms/labels_get.md
  api/descriptions/vms/names_get.md
  api/descriptions/vms/vms.md
  api/supported.cfg
Labels: bug, compute-api, docs

#713 [Compute AG] Update the screenshot for Defender scan time
  compute/admin_guide/_graphics/configure_scan_intervals_defender_details.png
  compute/admin_guide/configure/configure_scan_intervals.adoc
Labels: docs

#718 [Compute RN PCCE]: Kepler Update 5
  cspm/rn/book.yml
  cspm/rn/prisma-cloud-compute-release-information/features-introduced-in-compute-december-2022.adoc
  cspm/rn/prisma-cloud-compute-release-information/prisma-cloud-compute-release-information.adoc
Labels: docs, tested

#721 [Compute RN] Remove extra whitespace at end of file
  compute/rn/release-information/release-notes-22-12.adoc
Labels: tested

#733 GH36782 : Pending updates for risk tree in Admin and API reference
  api/descriptions/stats/vulnerabilities_download_get.md
  api/descriptions/stats/vulnerabilities_get.md
  api/descriptions/stats/vulnerabilities_impacted_resources_download_get.md
  api/descriptions/stats/vulnerabilities_impacted_resources_get.md
  compute/admin_guide/_graphics/ext-link-icon-small.png
  compute/admin_guide/vulnerability_management/risk_tree.adoc
Labels: docs

#731 [Compute RN On-prem]: Add a known issue for CWP-43836
  compute/rn/release-information/known-issues-22-12.adoc
Labels: tested, compute-rn

#689 [GH#36816 #38187] Update WAAS API discovery and VPC traffic mirroring
  compute/admin_guide/_graphics/aws_agentless_permissions_stack.png
  compute/admin_guide/_graphics/aws_agentless_setup_stack.png
  compute/admin_guide/_graphics/waas-api-discovery.png
  compute/admin_guide/_graphics/waas-sensitive-data.png
  compute/admin_guide/waas/deploy_waas/deployment_out_of_band.adoc
  compute/admin_guide/waas/deploy_waas/deployment_vpc_mirroring.adoc
  compute/admin_guide/waas/log_scrubbing.adoc
  compute/admin_guide/waas/waas_api_observation.adoc
  compute/admin_guide/waas/waas_custom_rules.adoc
Labels: docs, tested

#703 Corrections-topic-map-and-MD-files
  api/_topic_map.yml
  api/descriptions/agentless/agentless.md
  api/descriptions/audits/audits.md
  api/descriptions/certs/capem_get.md
  api/descriptions/certs/certs.md
  api/descriptions/certs/server-certs_get.md
  api/descriptions/version/get.md
  api/descriptions/vms/vms.md
Labels: bug, compute-api, docs

#702 [Compute API] CWP-43394: Correct "premissions" to "permission" in post_agentless_templates.md
  api/descriptions/agentless/post_agentless_templates.md
Labels: bug, compute-api, docs

#691 [Compute AG][GH#36810] Update JFrog Artifactory
  compute/admin_guide/_graphics/jfrogArtifactory-ca.png
  compute/admin_guide/vulnerability_management/registry_scanning/configure_registry_scanning.adoc
  compute/admin_guide/vulnerability_management/registry_scanning/scan_artifactory.adoc
Labels: docs, tested

#717 [Compute AG]: GH#36823 - Remove duplicate on-demand scan note
  compute/admin_guide/vulnerability_management/registry_scanning/configure_registry_scanning.adoc
Labels: docs, tested

#714 [Compute AG][GH#33333] Effects per protection in container runtime po…
  compute/admin_guide/_graphics/containerRuntimeRule-Networking.png
  compute/admin_guide/_graphics/containerRuntimeRule-Processes.png
  compute/admin_guide/runtime_defense/runtime_audits.adoc
  compute/admin_guide/runtime_defense/runtime_defense_containers.adoc
Labels: docs, tested

#722 [Compute AG - WAAS]: Updating WAAS intro
  compute/admin_guide/waas/waas-intro.adoc
Labels: docs, tested

#725 [Compute AG]: Vulnerability Management minor fixes
  compute/admin_guide/vulnerability_management/base_images.adoc
  compute/admin_guide/vulnerability_management/vuln_management_rules.adoc
Labels: docs, tested

#737 [Compute AG][CWP-37836] Mention image ID in description
  compute/admin_guide/tools/twistcli_scan_images.adoc
Labels: docs, tested

#735 [Compute AG][CWP-34764] Clarify Java 8 support
  compute/admin_guide/install/system_requirements.adoc
Labels: docs

#738 [CSPM AG] AWS topics updated post-22.12.1
  cspm/admin-guide/_graphics/aws-onboarding-aws-specify-stack-details-1.png
  cspm/admin-guide/_graphics/aws-onboarding-review-status-1.png
  cspm/admin-guide/_graphics/aws-onboarding-select-member-accts-1.png
  cspm/admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/add-aws-cloud-account-to-prisma-cloud.adoc
  cspm/admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/add-aws-member-accounts-to-prisma-cloud.adoc
  cspm/admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/add-aws-organization-to-prisma-cloud.adoc
  cspm/admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/enable-dns-logs-ingestion.adoc
  cspm/admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/enable-flow-logs-for-amazon-s3.adoc
  cspm/admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/update-an-onboarded-aws-account.adoc
  cspm/admin-guide/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.adoc
  cspm/admin-guide/prisma-cloud-data-security/troubleshoot-data-security-errors.adoc
Labels: tested, cspm ag

#739 [CodeSec AG] Add Azure to Drift Detection [RLP-82183]
  code-security/admin_guide/scan-monitor/drift-detection.adoc
Labels: tested

#743 [Compute RN PCEE]: Lagrange RN for SaaS
  .gitignore
  cspm/rn/_graphics/28934-accountid-filter-serverless.png
  cspm/rn/_graphics/36697-vulnerability-report-package.png
  cspm/rn/_graphics/36812-agentless-results.png
  cspm/rn/_graphics/38112-fix-status-version.png
  cspm/rn/_graphics/38289-cve-fix-date.png
  cspm/rn/_graphics/GH-36866-cloud-accounts.png
  cspm/rn/_graphics/GH-37159-alerts-sqs.png
  cspm/rn/_graphics/GH-37159-sqs-integration.png
  cspm/rn/_graphics/alert-trigger-profile.png
  cspm/rn/_graphics/application-host-control-compliance-rule.png
  cspm/rn/_graphics/containerRuntimeRule-Networking.png
  cspm/rn/_graphics/containerRuntimeRule-Processes.png
  cspm/rn/_graphics/custom-ca-certificate.png
  cspm/rn/_graphics/exclude-base-image-vulnerabilities.png
  cspm/rn/_graphics/rn-37326-vuln_explorer_image_details.png
  cspm/rn/_graphics/vulnerability-blocked-severitiy-risk-factor.png
  cspm/rn/_graphics/waas-access-control-exception.png
  cspm/rn/_graphics/waas-agentless-rule.png
  cspm/rn/_graphics/waas-api-discovery.png
  cspm/rn/_graphics/waas-custom-rules-jwt-functions.png
  cspm/rn/_graphics/waas-oob-tls.png
  cspm/rn/_graphics/waas-sensitive-data.png
  cspm/rn/_graphics/waas-vpc-configuration.png
  cspm/rn/_graphics/waas_custom_rules_min_defender.png
  cspm/rn/prisma-cloud-compute-release-information/features-introduced-in-compute-december-2022.adoc
  cspm/rn/prisma-cloud-compute-release-information/look-ahead-planned-updates-prisma-cloud-compute.adoc
  cspm/rn/prisma-cloud-compute-release-information/prisma-cloud-compute-known-issues.adoc
  cspm/rn/prisma-cloud-compute-release-information/prisma-cloud-compute-release-information.adoc
Labels: do-not-merge, tested, compute-rn

#729 [Compute AG Agentless] Add OCI onboarding flow
  compute/admin_guide/_graphics/agentless-add-account.png
  compute/admin_guide/_graphics/agentless-manage-cloud-accounts-pcee.png
  compute/admin_guide/_graphics/agentless-manage-cloud-accounts.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration-fingerprint.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration-name.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration-next.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration-private-key.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration-tenancy.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration-user.png
  compute/admin_guide/_graphics/agentless-oci-account-configuration.png
  compute/admin_guide/_graphics/agentless-oci-add-account.png
  compute/admin_guide/_graphics/agentless-oci-add-api-key.png
  compute/admin_guide/_graphics/agentless-oci-add-key-button.png
  compute/admin_guide/_graphics/agentless-oci-agentless-advanced-settings.png
  compute/admin_guide/_graphics/agentless-oci-agentless-configuration-add-account.png
  compute/admin_guide/_graphics/agentless-oci-agentless-configuration-compartment.png
  compute/admin_guide/_graphics/agentless-oci-agentless-configuration-download-template.png
  compute/admin_guide/_graphics/agentless-oci-agentless-configuration-url.png
  compute/admin_guide/_graphics/agentless-oci-api-keys.png
  compute/admin_guide/_graphics/agentless-oci-cloud-shell.png
  compute/admin_guide/_graphics/agentless-oci-configuration-file-preview-close.png
  compute/admin_guide/_graphics/agentless-oci-configuration-file-preview-fields.png
  compute/admin_guide/_graphics/agentless-oci-configuration-file-preview.png
  compute/admin_guide/_graphics/agentless-oci-create-compartments-name.png
  compute/admin_guide/_graphics/agentless-oci-create-compartments.png
  compute/admin_guide/_graphics/agentless-oci-create-user-button.png
  compute/admin_guide/_graphics/agentless-oci-create-user-fields.png
  compute/admin_guide/_graphics/agentless-oci-create-user.png
  compute/admin_guide/_graphics/agentless-oci-download-private-key.png
  compute/admin_guide/_graphics/agentless-oci-home.png
  compute/admin_guide/_graphics/agentless-oci-id-menu-compartments.png
  compute/admin_guide/_graphics/agentless-oci-id-menu-users.png
  compute/admin_guide/_graphics/agentless-oci-id-menu.png
  compute/admin_guide/_graphics/agentless-oci-upload-file.png
  compute/admin_guide/_graphics/agentless-oci-user.png
  compute/admin_guide/_graphics/agentless-start-scan-button.png
  compute/admin_guide/_graphics/agentless-stop-scan.png
  compute/admin_guide/_graphics/prisma-cloud-console-pcee.png
  compute/admin_guide/agentless-scanning/onboard-accounts/onboard-oci.adoc
  compute/admin_guide/book_compute_edition.yml
  compute/admin_guide/book_prisma_cloud.yml
Labels: docs, tested

#744 [CSPM AG] Tenable-integration
  cspm/admin-guide/_graphics/tenable-audit-trail.png
  cspm/admin-guide/_graphics/tenable-findings-trail.png
  cspm/admin-guide/_graphics/tenable-host-findings-view.png
  cspm/admin-guide/_graphics/tenable-hostfinding-config-query.png
  cspm/admin-guide/_graphics/tenable-int-2.png
  cspm/admin-guide/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-tenable.adoc
Labels: tested, cspm ag

#745 [Compute AG - WAAS]: Update sensitive data pattern-based rule
  compute/admin_guide/waas/log_scrubbing.adoc
Labels: docs, tested, compute-AG

#759 [Compute AG]: Fix images and syntax in JFrog Artifactory
  compute/admin_guide/vulnerability_management/registry_scanning/scan_artifactory.adoc
Labels: tested, compute-AG

#760 [Compute AG: CWP-42741] Add kaniko image vuln. filtering limitation
  compute/admin_guide/vulnerability_management/base_images.adoc
  compute/admin_guide/vulnerability_management/vuln_management_rules.adoc
Labels: docs, tested, compute-AG
