Repository PaloAltoNetworks/prisma-cloud-docs, pull requests merged in 2022-08, with the labels that each got.

#447 [#39757+#39658]:Improve Vulnerability doc
  compute/admin_guide/vulnerability_management/detect_vulns_unpackaged_software.adoc
Labels: docs

#467 Agentless configuration edits
  compute/admin_guide/_graphics/agentless-permission-templates.png
  compute/admin_guide/configure/configure-agentless-scanning.adoc
Labels: docs

#327 Add new Enforcer Installation procedures
  cns/saas/admin_guide/_graphics/api-server-install.png
  cns/saas/admin_guide/_graphics/cloud-registration-1.png
  cns/saas/admin_guide/_graphics/cloud-registration-2.png
  cns/saas/admin_guide/_graphics/cloud-registration-3.png
  cns/saas/admin_guide/_graphics/cloud-registration-4.png
  cns/saas/admin_guide/_graphics/create-namespace-cloud-account-1.png
  cns/saas/admin_guide/_graphics/create-namespace-group-1.png
  cns/saas/admin_guide/_graphics/create-network-list-1.png
  cns/saas/admin_guide/_graphics/create-network-list-2.png
  cns/saas/admin_guide/_graphics/create-network-list-3.png
  cns/saas/admin_guide/_graphics/create-network-list-4.png
  cns/saas/admin_guide/_graphics/enable-host-mode.png
  cns/saas/admin_guide/_graphics/enforcer-aks-1.png
  cns/saas/admin_guide/_graphics/enforcer-aks-2.png
  cns/saas/admin_guide/_graphics/enforcer-eks-1.png
  cns/saas/admin_guide/_graphics/enforcer-eks-2.png
  cns/saas/admin_guide/_graphics/enforcer-gke-1.png
  cns/saas/admin_guide/_graphics/enforcer-gke-2.png
  cns/saas/admin_guide/_graphics/enforcer-gke-21.png
  cns/saas/admin_guide/_graphics/enforcer-ocp4-1.png
  cns/saas/admin_guide/_graphics/enforcer-ocp4-2.png
  cns/saas/admin_guide/_graphics/flow-logs-create-external-network-suggestion.png
  cns/saas/admin_guide/_graphics/flow-logs-create-external-networks.png
  cns/saas/admin_guide/_graphics/install-enforcer-1.png
  cns/saas/admin_guide/_graphics/install-enforcer-10.png
  cns/saas/admin_guide/_graphics/install-enforcer-11.png
  cns/saas/admin_guide/_graphics/install-enforcer-2.png
  cns/saas/admin_guide/_graphics/install-enforcer-3.png
  cns/saas/admin_guide/_graphics/install-enforcer-4.png
  cns/saas/admin_guide/_graphics/install-enforcer-5.png
  cns/saas/admin_guide/_graphics/install-enforcer-6.png
  cns/saas/admin_guide/_graphics/install-enforcer-7.png
  cns/saas/admin_guide/_graphics/install-enforcer-9.png
  cns/saas/admin_guide/_graphics/monitor-flows-after.png
  cns/saas/admin_guide/_graphics/monitor-flows.png
  cns/saas/admin_guide/_graphics/practical-application-example.png
  cns/saas/admin_guide/book.yml
  cns/saas/admin_guide/concepts/monitor-network-traffic.adoc
  cns/saas/admin_guide/configure/create-external-networks.adoc
  cns/saas/admin_guide/start/create-ns.adoc
  cns/saas/admin_guide/start/enforcer/enforcer.adoc
  cns/saas/admin_guide/start/enforcer/k8s.adoc
  cns/saas/admin_guide/start/enforcer/linux.adoc
  cns/saas/admin_guide/start/enforcer/windows.adoc
  cns/saas/admin_guide/start/reqs.adoc
  cns/saas/admin_guide/start/start.adoc
Labels: docs

#503 [Compute API] API issue # 40773 - Remove unsupported endpoints and update missing titles
  api/_topic_map.yml
  api/descriptions/defenders/serverless-bundle_post.md
  api/descriptions/util/dbip_countrylite_get.md
  api/descriptions/util/osx_twistcli_get.md
  api/descriptions/util/twistlock_jenkins_plugin_get.md
  api/descriptions/util/windows_twistcli_get.md
  api/supported.cfg
Labels: compute-api, docs

#520 [Do not merge] Corrections: Rebuild from master and updates to Topic Map, CFG, and descriptions
  api/README.md
  api/_topic_map.yml
  api/descriptions/util/twistlock_jenkins_plugin_get.md
  api/supported.cfg
Labels: compute-api, do-not-merge, docs
